import { getFollowAlongAudioUrl, hashFollowAlongNarration } from './audioGuide.js';

/**
 * Generated by the Start Here audio promotion workflow after owner approval.
 * An empty manifest fails closed: controls stay visible but disabled and no
 * unapproved or stale narration is requested by the browser.
 */
export const START_HERE_AUDIO_MANIFEST = Object.freeze({
    status: 'pending-owner-full-listen-through',
    scriptBundleSha256: null,
    clips: Object.freeze({})
});

export function resolveApprovedStartHereAudioUrl(
    narration,
    {
        allowLocalReview = import.meta.env?.DEV === true,
        manifest = START_HERE_AUDIO_MANIFEST,
        baseUrl = import.meta.env?.BASE_URL || '/'
    } = {}
) {
    const contentId = hashFollowAlongNarration(narration);
    if (allowLocalReview) {
        return getFollowAlongAudioUrl(narration, baseUrl);
    }
    if (
        manifest?.status !== 'approved'
        || manifest?.clips?.[contentId] !== true
    ) {
        return null;
    }
    return getFollowAlongAudioUrl(narration, baseUrl);
}
